artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://archive.ics.uci.edu/ml/machine-learning-databases/concrete/compressive/Concrete_Data.xls
  local_data_file: artifacts/data_ingestion/Concrete_Data.xls
  
data_validation:
  root_dir: artifacts/data_validation
  data_validation_path: artifacts/data_ingestion/Concrete_Data.xls
  updated_data_validation_path: artifacts/data_validation/concrete_updated_data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_transformation_path: concrete_updated_data.csv